FROM --platform=amd64  ubuntu:20.04
COPY requirements.txt .
ENV DEBIAN_FRONTEND noninteractive
RUN useradd -ms /bin/bash --uid 1000 jupyter\
&& apt update\
&& apt install -y python3.8-dev python3.8-distutils curl wget\
&& ln -s /usr/bin/python3.8 /usr/local/bin/python3\
&& curl https://bootstrap.pypa.io/get-pip.py | python3\
&& apt autoremove --yes &&\
apt clean -y &&\
rm -rf /var/lib/{apt,dpkg,cache,log}/
RUN pip3 install --no-cache-dir --upgrade pip && pip3 install -r requirements.txt
  